/**
 * Birthplaces of the two great missionaries of Acts — Saul/Paul (Tarsus
 * of Cilicia, Acts 22:3) and Barnabas (Cyprus, Acts 4:36; Salamis is his
 * traditional hometown and the first stop of the First Missionary
 * Journey, Acts 13:5).
 *
 * This is a committed, hand-authored module (NOT generated by the data
 * pipeline) because the generated GeoJSON files are git-ignored and
 * regenerated on every build. All display strings live in the i18n
 * dictionaries under `t.birthplaces.*` so they translate; only the
 * geography and the "jump to verse" target live here.
 *
 * Coordinate order is [lon, lat] everywhere in this codebase.
 */

export type BirthplaceId = 'paul' | 'barnabas';

export interface Birthplace {
  id: BirthplaceId;
  lon: number;
  lat: number;
  /** Acts chapter/verse for the "Open in Scripture →" popup link. */
  chapter: number;
  verse: number;
  /**
   * Language-neutral search haystack (English + Kinyarwanda spellings)
   * so the map search finds these pins regardless of the active
   * language. Lowercase, space-separated.
   */
  keywords: string;
}

export const BIRTHPLACES: Birthplace[] = [
  // Tarsus of Cilicia — "I am a Jew, born in Tarsus of Cilicia" (Acts 22:3)
  {
    id: 'paul', lon: 34.8956, lat: 36.9168, chapter: 22, verse: 3,
    keywords: 'tarsus taruso cilicia kilikiya paul pawulo saul sawuli',
  },
  // Cyprus (Salamis) — "Joseph, a Levite, a native of Cyprus" (Acts 4:36)
  {
    id: 'barnabas', lon: 33.901, lat: 35.181, chapter: 4, verse: 36,
    keywords: 'salamis salami cyprus kupuro barnabas barinaba joseph yosefu',
  },
];
